
package eseo.sw.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Thu Mar 29 12:55:11 CEST 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "trouverChambreResponse", namespace = "http://sw.eseo/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverChambreResponse", namespace = "http://sw.eseo/")

public class TrouverChambreResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<eseo.sw.Chambre> _return;

    public java.util.ArrayList<eseo.sw.Chambre> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<eseo.sw.Chambre> new_return)  {
        this._return = new_return;
    }

}

